export const ON_IMAGE_LOAD = 'ON_IMAGE_LOAD';
export const SHORTCUT = 'SHORTCUT';
export const CHANGE_LABEL_TEXT = 'CHANGE_LABEL_TEXT';
export const MOVE = 'MOVE';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';

export const SELECT_POINT = 'SELECT_POINT';
export const DESELECT_POINT = 'DESELECT_POINT';
export const ENTER_POINT = 'ENTER_POINT';
export const LEAVE_POINT = 'LEAVE_POINT';

export const SELECT_SHAPE = 'SELECT_SHAPE';
export const DESELECT_SHAPE = 'DESELECT_SHAPE';
export const ENTER_SHAPE = 'ENTER_SHAPE';
export const LEAVE_SHAPE = 'LEAVE_SHAPE';

export const ADD_POINT = 'ADD_POINT';
export const BEGIN_TO_DRAG_PRE_ANNOTATION = 'BEGIN_TO_DRAG_PRE_ANNOTATION';
export const END_OF_DRAG_PRE_ANNOTATION = 'END_OF_DRAG_PRE_ANNOTATION';
export const DRAG_PRE_ANNOTATION = 'DRAG_PRE_ANNOTATION';
export const ENTER_PRE_POINT = 'ENTER_PRE_POINT';
export const LEAVE_PRE_POINT = 'LEAVE_PRE_POINT';
export const CLICK_PRE_POINT = 'CLICK_PRE_POINT';
